### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mangeshsable1975** [manddar/Open-Interest-Data-Extractor#3]
![error](https://user-images.githubusercontent.com/67979855/142774108-860fa34c-0ca8-437a-827e-6a34f3ffdeed.png)

**Comment by manddar** [comment]
Hello @mangeshsable1975 

I know this is very late, but can you check script again and let me know if it works fine.

br,
Mandar

**Comment by mangeshsable1975** [comment]
Sorry mandar for late reply,
I am out of city for some time I will get back to you when I will be back

Thanking you,

Mangesh sable
